version: '3.8'  

services:
  db:
    container_name: products_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Lihobor
      POSTGRES_DB: products
    ports:
      - "5432:5432"
  app:
    container_name: sales_app
    build: ./
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: postgresql://postgres:@products_db:5432/products
    volumes:
      - ./app:/code/app
    depends_on:
      - db
  redis:
    container_name: redis_for_sales
    image: redis:7
  celery:
    container_name: celery_worker
    build: ./
    command: celery -A settings.celery_settings.celery_app worker --loglevel=info
  celery_beat:
    container_name: celery_beat
    build: ./
    command: celery -A settings.celery_settings.celery_app beat --schedule ./celery_beat/celerybeat-schedule --loglevel=info