"""add new model and fields

Revision ID: 94fdf23459fb
Revises: c03219e465ee
Create Date: 2024-11-17 19:36:48.058601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94fdf23459fb'
down_revision: Union[str, None] = 'c03219e465ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('product', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'date')
    op.drop_table('analys')
    # ### end Alembic commands ###
